### ISSUE TITLE
Enhancement: Make fan speed change persistant

### ISSUE THREAD

**Issue by sfrebel** [ntoff/OctoPrint-FanSpeedSlider#10]
Great plugin first of all.
A great addition would be to have the option to make the fan speed change persistant, e.g. ignore all M106 and keep the fan speed as set by the user untill this option is disabled.

**Comment by ntoff** [comment]
Give this branch a test. https://github.com/ntoff/OctoPrint-FanSpeedSlider/tree/commandlocktest

It has a padlock button next to the "fan off" button, seemed like the most aesthetically pleasing place to put it, and there's also the same function added to the settings page.

It should disable the fan buttons on the controls page, and also reject M106 / M107 commands and stop them reaching the printer.

It'd be super helpful if you could give it a test and see if it works for you (tested here and it all seems to work).

**Comment by ntoff** [comment]
Since I haven't heard anything, I'll assume your tests were successful. Feature added to 0.2.0 and released.
