### ISSUE TITLE
Regular expression in __init.py__ is incorrect

### ISSUE THREAD

**Issue by b-morgan** [ntoff/OctoPrint-FanSpeedSlider#9]
In __init.py__ the line "fanPwm = re.search("S(\d+.\d+)", cmd)" only matches 3 digit values. It should be "fanPwm = re.search("S(\d+\\.?\d*)", cmd)".

**Comment by ntoff** [comment]
Thanks. Regexp's are the devil's magic as far as I'm concerned, I have no idea how they work.

**Comment by ntoff** [comment]
Closing since I implemented your fix and published it. Thanks for the report, and the fix.
